version: "3.7"

services:
  clientelo:
    image: maven:3.8.6-eclipse-temurin-17
    working_dir: /usr/src/clientelo
    volumes:
      - ./:/usr/src/clientelo
      - ./target:/usr/src/clientelo/target
      - $HOME/.m2:/root/.m2
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=clientelo
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=clientelo
    volumes:
      - ./db:/var/lib/mysql